//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company &quot;Id&quot; &lt; 1.
        /// </summary>
        public static string Company_Id_LessOne {
            get {
                return ResourceManager.GetString("Company_Id_LessOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company &quot;Id&quot; is null.
        /// </summary>
        public static string Company_Id_Null {
            get {
                return ResourceManager.GetString("Company_Id_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company &quot;Name&quot; is empty.
        /// </summary>
        public static string Company_Name_Empty {
            get {
                return ResourceManager.GetString("Company_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found or deleted.
        /// </summary>
        public static string Company_NotFoundOrDeleted {
            get {
                return ResourceManager.GetString("Company_NotFoundOrDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Company&quot; is null.
        /// </summary>
        public static string Company_Null {
            get {
                return ResourceManager.GetString("Company_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company &quot;Users&quot; is empty.
        /// </summary>
        public static string Company_Users_Empty {
            get {
                return ResourceManager.GetString("Company_Users_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company &quot;User&quot; is invalid.
        /// </summary>
        public static string Company_Users_Invalid {
            get {
                return ResourceManager.GetString("Company_Users_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Criteria&quot; is null.
        /// </summary>
        public static string Criteria_Null {
            get {
                return ResourceManager.GetString("Criteria_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Id&quot; &lt; 1.
        /// </summary>
        public static string Id_LessOne {
            get {
                return ResourceManager.GetString("Id_LessOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both &quot;Role&quot; and &quot;User&quot; are null.
        /// </summary>
        public static string Role_and_User_Null {
            get {
                return ResourceManager.GetString("Role_and_User_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;Email&quot; is empty.
        /// </summary>
        public static string User_Email_Empty {
            get {
                return ResourceManager.GetString("User_Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;EULA&quot; is not accepted.
        /// </summary>
        public static string User_Eula_NotAccepted {
            get {
                return ResourceManager.GetString("User_Eula_NotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;GDPR&quot; is not accepted.
        /// </summary>
        public static string User_Gdpr_NotAccepted {
            get {
                return ResourceManager.GetString("User_Gdpr_NotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;Id&quot; &lt; 1.
        /// </summary>
        public static string User_Id_LessOne {
            get {
                return ResourceManager.GetString("User_Id_LessOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;Id&quot; is null.
        /// </summary>
        public static string User_Id_Null {
            get {
                return ResourceManager.GetString("User_Id_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;Name&quot; is empty.
        /// </summary>
        public static string User_Name_Empty {
            get {
                return ResourceManager.GetString("User_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;User&quot; is null.
        /// </summary>
        public static string User_Null {
            get {
                return ResourceManager.GetString("User_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;Password&quot; is empty.
        /// </summary>
        public static string User_Password_Empty {
            get {
                return ResourceManager.GetString("User_Password_Empty", resourceCulture);
            }
        }
    }
}
