// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebLicense.Access;

namespace WebLicense.Access.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210725095241_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasComment("Secure ID of the Customer.");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("The Name of the Customer");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasComment("Reference ID is using to register new users for the Customer.");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.CompanySettings", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanActivateLicenses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanActivateMachines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDeactivateLicenses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDeactivateMachines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDeleteLicenses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDeleteMachines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateActiveLicenses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxActiveLicensesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTotalLicensesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationsEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Email address used for notifications.");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("INTEGER")
                        .HasComment("Must be TRUE if Customer wants to receive notifications about his licenses.");

                    b.HasKey("CompanyId", "ProviderCompanyId");

                    b.HasIndex("ProviderCompanyId");

                    b.HasIndex("ReceiveNotifications");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.CompanyUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Changes")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Created");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUpdates");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.CompanyUser", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManager")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompanyId", "UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IsManager");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.CompanyUserInvite", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManager")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Processed")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompanyId", "Email");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.HasIndex("Created");

                    b.HasIndex("Email");

                    b.HasIndex("Processed");

                    b.ToTable("CompanyUserInvites");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 9223372036854775807L,
                            ConcurrencyStamp = "0a50d526-a713-4338-9ad3-719932ee6ec9",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 9223372036854775806L,
                            ConcurrencyStamp = "015eac73-8122-484e-8e12-ebec128761e2",
                            Name = "Customer Admin",
                            NormalizedName = "CUSTOMER ADMIN"
                        },
                        new
                        {
                            Id = 9223372036854775805L,
                            ConcurrencyStamp = "899099a1-0f47-464b-9948-b7b8989c4124",
                            Name = "Customer Manager",
                            NormalizedName = "CUSTOMER MANAGER"
                        },
                        new
                        {
                            Id = 9223372036854775804L,
                            ConcurrencyStamp = "8c59273e-1dcb-4088-b0a0-96feb0dc2181",
                            Name = "Customer User",
                            NormalizedName = "CUSTOMER USER"
                        });
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");

                    b.HasData(
                        new
                        {
                            Id = 2147483647,
                            ClaimType = "https://weblicense/account/password/change",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483646,
                            ClaimType = "https://weblicense/account/2fa/disable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483645,
                            ClaimType = "https://weblicense/account/2fa/enable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483644,
                            ClaimType = "https://weblicense/account/login/external",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483643,
                            ClaimType = "https://weblicense/account/password/reset",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483642,
                            ClaimType = "https://weblicense/administration/account/password/change",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483641,
                            ClaimType = "https://weblicense/administration/account/2fa/disable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483640,
                            ClaimType = "https://weblicense/administration/account/2fa/enable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483639,
                            ClaimType = "https://weblicense/administration/account/password/reset",
                            ClaimValue = "true",
                            RoleId = 9223372036854775807L
                        },
                        new
                        {
                            Id = 2147483547,
                            ClaimType = "https://weblicense/account/password/change",
                            ClaimValue = "true",
                            RoleId = 9223372036854775806L
                        },
                        new
                        {
                            Id = 2147483546,
                            ClaimType = "https://weblicense/account/2fa/disable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775806L
                        },
                        new
                        {
                            Id = 2147483545,
                            ClaimType = "https://weblicense/account/2fa/enable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775806L
                        },
                        new
                        {
                            Id = 2147483544,
                            ClaimType = "https://weblicense/account/login/external",
                            ClaimValue = "true",
                            RoleId = 9223372036854775806L
                        },
                        new
                        {
                            Id = 2147483543,
                            ClaimType = "https://weblicense/account/password/reset",
                            ClaimValue = "true",
                            RoleId = 9223372036854775806L
                        },
                        new
                        {
                            Id = 2147483447,
                            ClaimType = "https://weblicense/account/password/change",
                            ClaimValue = "true",
                            RoleId = 9223372036854775805L
                        },
                        new
                        {
                            Id = 2147483446,
                            ClaimType = "https://weblicense/account/2fa/disable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775805L
                        },
                        new
                        {
                            Id = 2147483445,
                            ClaimType = "https://weblicense/account/2fa/enable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775805L
                        },
                        new
                        {
                            Id = 2147483444,
                            ClaimType = "https://weblicense/account/login/external",
                            ClaimValue = "true",
                            RoleId = 9223372036854775805L
                        },
                        new
                        {
                            Id = 2147483443,
                            ClaimType = "https://weblicense/account/password/reset",
                            ClaimValue = "true",
                            RoleId = 9223372036854775805L
                        },
                        new
                        {
                            Id = 2147483347,
                            ClaimType = "https://weblicense/account/password/change",
                            ClaimValue = "true",
                            RoleId = 9223372036854775804L
                        },
                        new
                        {
                            Id = 2147483346,
                            ClaimType = "https://weblicense/account/2fa/disable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775804L
                        },
                        new
                        {
                            Id = 2147483345,
                            ClaimType = "https://weblicense/account/2fa/enable",
                            ClaimValue = "true",
                            RoleId = 9223372036854775804L
                        },
                        new
                        {
                            Id = 2147483344,
                            ClaimType = "https://weblicense/account/login/external",
                            ClaimValue = "true",
                            RoleId = 9223372036854775804L
                        },
                        new
                        {
                            Id = 2147483343,
                            ClaimType = "https://weblicense/account/password/reset",
                            ClaimValue = "true",
                            RoleId = 9223372036854775804L
                        });
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EulaAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GdprAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 9223372036854775807L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c25734a-1c0a-49da-936f-61d8e0fe72aa",
                            Email = "admin-one@weblicense.com",
                            EmailConfirmed = true,
                            EulaAccepted = true,
                            GdprAccepted = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN-ONE@WEBLICENSE.COM",
                            NormalizedUserName = "ADMINISTRATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAELfRIkHUzs1mo9e8ibm7MeFRCeWKE6CGzPMxHM7Hhc3PF4qcHTyy8dg7WN3poZsi5w==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "BDD22C5C1C8B41E280AFB89135ECBF5C85096EDF1FA045C9B73C2C400843F941897CD31D11B74298910466D7E90247ED",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        });
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("RoleId", "UserId")
                        .IsUnique();

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 9223372036854775807L,
                            RoleId = 9223372036854775807L
                        });
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.UserToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.CompanySettings", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Companies.Company", "Company")
                        .WithMany("Settings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebLicense.Core.Models.Companies.Company", "ProviderCompany")
                        .WithMany("ClientSettings")
                        .HasForeignKey("ProviderCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ProviderCompany");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.CompanyUpdate", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Companies.Company", "Company")
                        .WithMany("Updates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebLicense.Core.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.CompanyUser", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Companies.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebLicense.Core.Models.Identity.User", "User")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.CompanyUserInvite", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Companies.Company", "Company")
                        .WithMany("CompanyUserInvites")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.RoleClaim", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.UserClaim", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.UserLogin", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.UserRole", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebLicense.Core.Models.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.UserToken", b =>
                {
                    b.HasOne("WebLicense.Core.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebLicense.Core.Models.Companies.Company", b =>
                {
                    b.Navigation("ClientSettings");

                    b.Navigation("CompanyUserInvites");

                    b.Navigation("CompanyUsers");

                    b.Navigation("Settings");

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("WebLicense.Core.Models.Identity.User", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
