//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Shared.Resources.Model", typeof(Model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Code.
        /// </summary>
        public static string Customer_Code {
            get {
                return ResourceManager.GetString("Customer-Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Name.
        /// </summary>
        public static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer-Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##ReferenceId.
        /// </summary>
        public static string Customer_ReferenceId {
            get {
                return ResourceManager.GetString("Customer-ReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Can activate Licenses.
        /// </summary>
        public static string Customer_Settings_CanActivateLicenses {
            get {
                return ResourceManager.GetString("Customer-Settings-CanActivateLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Can activate Machines.
        /// </summary>
        public static string Customer_Settings_CanActivateMachines {
            get {
                return ResourceManager.GetString("Customer-Settings-CanActivateMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Can deactivate Licenses.
        /// </summary>
        public static string Customer_Settings_CanDeactivateLicenses {
            get {
                return ResourceManager.GetString("Customer-Settings-CanDeactivateLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Can deactivate Machines.
        /// </summary>
        public static string Customer_Settings_CanDeactivateMachines {
            get {
                return ResourceManager.GetString("Customer-Settings-CanDeactivateMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Can delete Licenses.
        /// </summary>
        public static string Customer_Settings_CanDeleteLicenses {
            get {
                return ResourceManager.GetString("Customer_Settings_CanDeleteLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Can delete Machines.
        /// </summary>
        public static string Customer_Settings_CanDeleteMachines {
            get {
                return ResourceManager.GetString("Customer-Settings-CanDeleteMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Create new Licenses activated by default.
        /// </summary>
        public static string Customer_Settings_CreateActiveLicenses {
            get {
                return ResourceManager.GetString("Customer-Settings-CreateActiveLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Maximum active Licenses.
        /// </summary>
        public static string Customer_Settings_MaxActiveLicensesCount {
            get {
                return ResourceManager.GetString("Customer-Settings-MaxActiveLicensesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Maximum total Licenses.
        /// </summary>
        public static string Customer_Settings_MaxTotalLicensesCount {
            get {
                return ResourceManager.GetString("Customer-Settings-MaxTotalLicensesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Email for notifications.
        /// </summary>
        public static string Customer_Settings_NotificationsEmail {
            get {
                return ResourceManager.GetString("Customer-Settings-NotificationsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Want to receive notifications.
        /// </summary>
        public static string Customer_Settings_ReceiveNotifications {
            get {
                return ResourceManager.GetString("Customer-Settings-ReceiveNotifications", resourceCulture);
            }
        }
    }
}
