//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Shared.Resources.Model", typeof(Model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Code.
        /// </summary>
        public static string Company_Code {
            get {
                return ResourceManager.GetString("Company-Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Name.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company-Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ReferenceId.
        /// </summary>
        public static string Company_ReferenceId {
            get {
                return ResourceManager.GetString("Company-ReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Can activate Licenses.
        /// </summary>
        public static string Company_Settings_CanActivateLicenses {
            get {
                return ResourceManager.GetString("Company-Settings-CanActivateLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Can activate Machines.
        /// </summary>
        public static string Company_Settings_CanActivateMachines {
            get {
                return ResourceManager.GetString("Company-Settings-CanActivateMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Can deactivate Licenses.
        /// </summary>
        public static string Company_Settings_CanDeactivateLicenses {
            get {
                return ResourceManager.GetString("Company-Settings-CanDeactivateLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Can deactivate Machines.
        /// </summary>
        public static string Company_Settings_CanDeactivateMachines {
            get {
                return ResourceManager.GetString("Company-Settings-CanDeactivateMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Can delete Licenses.
        /// </summary>
        public static string Company_Settings_CanDeleteLicenses {
            get {
                return ResourceManager.GetString("Company_Settings_CanDeleteLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Can delete Machines.
        /// </summary>
        public static string Company_Settings_CanDeleteMachines {
            get {
                return ResourceManager.GetString("Company-Settings-CanDeleteMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Create new Licenses activated by default.
        /// </summary>
        public static string Company_Settings_CreateActiveLicenses {
            get {
                return ResourceManager.GetString("Company-Settings-CreateActiveLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Maximum active Licenses.
        /// </summary>
        public static string Company_Settings_MaxActiveLicensesCount {
            get {
                return ResourceManager.GetString("Company-Settings-MaxActiveLicensesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Maximum total Licenses.
        /// </summary>
        public static string Company_Settings_MaxTotalLicensesCount {
            get {
                return ResourceManager.GetString("Company-Settings-MaxTotalLicensesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Email for notifications.
        /// </summary>
        public static string Company_Settings_NotificationsEmail {
            get {
                return ResourceManager.GetString("Company-Settings-NotificationsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Want to receive notifications.
        /// </summary>
        public static string Company_Settings_ReceiveNotifications {
            get {
                return ResourceManager.GetString("Company-Settings-ReceiveNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Manager.
        /// </summary>
        public static string CompanyUser_IsManager {
            get {
                return ResourceManager.GetString("CompanyUser-IsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Two-factor authentication.
        /// </summary>
        public static string User_2FAEnabled {
            get {
                return ResourceManager.GetString("User-2FAEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Companies.
        /// </summary>
        public static string User_Companies {
            get {
                return ResourceManager.GetString("User-Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Email address.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User-Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Email confirmed.
        /// </summary>
        public static string User_EmailConfirmed {
            get {
                return ResourceManager.GetString("User-EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EULA.
        /// </summary>
        public static string User_EulaAccepted {
            get {
                return ResourceManager.GetString("User-EulaAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #GDPR.
        /// </summary>
        public static string User_GdprAccepted {
            get {
                return ResourceManager.GetString("User-GdprAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Is locked.
        /// </summary>
        public static string User_LockoutEnabled {
            get {
                return ResourceManager.GetString("User-LockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Locked until.
        /// </summary>
        public static string User_LockoutEnd {
            get {
                return ResourceManager.GetString("User-LockoutEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User-Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Phone number.
        /// </summary>
        public static string User_Phone {
            get {
                return ResourceManager.GetString("User-Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Phone confirmed.
        /// </summary>
        public static string User_PhoneConfirmed {
            get {
                return ResourceManager.GetString("User-PhoneConfirmed", resourceCulture);
            }
        }
    }
}
