//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_Manage_GenerateRecoveryCodesModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_Manage_GenerateRecoveryCodesModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.Manage.GenerateRecoveryC" +
                            "odesModel", typeof(Areas_Identity_Pages_Account_Manage_GenerateRecoveryCodesModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *User with ID &apos;{0}&apos; has generated new 2FA recovery codes..
        /// </summary>
        public static string Log_CodesGenerated {
            get {
                return ResourceManager.GetString("Log.CodesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Put these codes in a safe place..
        /// </summary>
        public static string Message_1 {
            get {
                return ResourceManager.GetString("Message.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string Message_2 {
            get {
                return ResourceManager.GetString("Message.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should.
        /// </summary>
        public static string Message_3_1 {
            get {
                return ResourceManager.GetString("Message.3.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *reset your authenticator keys.
        /// </summary>
        public static string Message_3_2 {
            get {
                return ResourceManager.GetString("Message.3.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Message_3_3 {
            get {
                return ResourceManager.GetString("Message.3.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You have generated new recovery codes..
        /// </summary>
        public static string Message_CodesGenerated {
            get {
                return ResourceManager.GetString("Message.CodesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Generate Recovery Codes.
        /// </summary>
        public static string Text_GenerateRecoveryCodes {
            get {
                return ResourceManager.GetString("Text.GenerateRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Generate two-factor authentication (2FA) recovery codes.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Cannot generate recovery codes for user with ID &apos;{0}&apos; because they do not have 2FA enabled..
        /// </summary>
        public static string Validation_2FANotEnabled {
            get {
                return ResourceManager.GetString("Validation.2FANotEnabled", resourceCulture);
            }
        }
    }
}
