//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_Manage_Disable2faModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_Manage_Disable2faModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.Manage.Disable2faModel", typeof(Areas_Identity_Pages_Account_Manage_Disable2faModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Unexpected error occurred disabling 2FA for user with ID &apos;{0}&apos;..
        /// </summary>
        public static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error.Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This action only disables 2FA..
        /// </summary>
        public static string Message_1 {
            get {
                return ResourceManager.GetString("Message.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should.
        /// </summary>
        public static string Message_2_1 {
            get {
                return ResourceManager.GetString("Message.2.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *reset your authenticator keys.
        /// </summary>
        public static string Message_2_2 {
            get {
                return ResourceManager.GetString("Message.2.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Message_2_3 {
            get {
                return ResourceManager.GetString("Message.2.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *2FA has been disabled. You can reenable 2FA when you setup an authenticator app.
        /// </summary>
        public static string Message_2FADisabledSuccessful_2 {
            get {
                return ResourceManager.GetString("Message.2FADisabledSuccessful-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *User with ID &apos;{0}&apos; has disabled 2FA..
        /// </summary>
        public static string Message_2FADisableSuccessful {
            get {
                return ResourceManager.GetString("Message.2FADisableSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Disable 2FA.
        /// </summary>
        public static string Text_Disable2FA {
            get {
                return ResourceManager.GetString("Text.Disable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Disable two-factor authentication (2FA).
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Cannot disable 2FA for user with ID &apos;{0}&apos; as it&apos;s not currently enabled..
        /// </summary>
        public static string Validation_2FANotEnabled {
            get {
                return ResourceManager.GetString("Validation.2FANotEnabled", resourceCulture);
            }
        }
    }
}
