//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_LoginModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_LoginModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.LoginModel", typeof(Areas_Identity_Pages_Account_LoginModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Invalid login attempt..
        /// </summary>
        public static string Error_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Error.InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Log in using your {0} account.
        /// </summary>
        public static string Format_LoginByUsingYourAccount {
            get {
                return ResourceManager.GetString("Format.LoginByUsingYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Email.
        /// </summary>
        public static string Model_Email {
            get {
                return ResourceManager.GetString("Model.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Password.
        /// </summary>
        public static string Model_Password {
            get {
                return ResourceManager.GetString("Model.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Remember me.
        /// </summary>
        public static string Model_RememberMe {
            get {
                return ResourceManager.GetString("Model.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Forgot your password?.
        /// </summary>
        public static string Question_ForgotPassword {
            get {
                return ResourceManager.GetString("Question.ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Log in.
        /// </summary>
        public static string Text_LogIn {
            get {
                return ResourceManager.GetString("Text.LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *There are no external authentication services configured..
        /// </summary>
        public static string Text_NoExternalAuthenticationProvidersConfigured {
            get {
                return ResourceManager.GetString("Text.NoExternalAuthenticationProvidersConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Register as a new user.
        /// </summary>
        public static string Text_RegisterAsNewUser {
            get {
                return ResourceManager.GetString("Text.RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Resend email confirmation.
        /// </summary>
        public static string Text_ResetEmailConfirmation {
            get {
                return ResourceManager.GetString("Text.ResetEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Use another service to log in..
        /// </summary>
        public static string Text_UseExternalServiceToLogin {
            get {
                return ResourceManager.GetString("Text.UseExternalServiceToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Use a local account to log in..
        /// </summary>
        public static string Text_UseLocalAccountToLogin {
            get {
                return ResourceManager.GetString("Text.UseLocalAccountToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Log in.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
