//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_Manage_EnableAuthenticatorModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_Manage_EnableAuthenticatorModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.Manage.EnableAuthenticat" +
                            "orModel", typeof(Areas_Identity_Pages_Account_Manage_EnableAuthenticatorModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *To use an authenticator app go through the following steps:.
        /// </summary>
        public static string Message_1 {
            get {
                return ResourceManager.GetString("Message-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Download a two-factor authenticator app like Microsoft Authenticator for.
        /// </summary>
        public static string Message_2 {
            get {
                return ResourceManager.GetString("Message-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Google Authenticator for.
        /// </summary>
        public static string Message_3 {
            get {
                return ResourceManager.GetString("Message-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Scan the QR Code or enter this key into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string Message_4 {
            get {
                return ResourceManager.GetString("Message-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string Message_5 {
            get {
                return ResourceManager.GetString("Message-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Your authenticator app has been verified..
        /// </summary>
        public static string Message_AuthentificatorVerificationSuccessful {
            get {
                return ResourceManager.GetString("Message.AuthentificatorVerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Verification Code.
        /// </summary>
        public static string Model_Code {
            get {
                return ResourceManager.GetString("Model.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string Text_And {
            get {
                return ResourceManager.GetString("Text.And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Android.
        /// </summary>
        public static string Text_Android {
            get {
                return ResourceManager.GetString("Text.Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *iOS.
        /// </summary>
        public static string Text_iOS {
            get {
                return ResourceManager.GetString("Text.iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Text_Or {
            get {
                return ResourceManager.GetString("Text.Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Verify.
        /// </summary>
        public static string Text_Verify {
            get {
                return ResourceManager.GetString("Text.Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Configure authenticator app.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Verification code is invalid..
        /// </summary>
        public static string Validation_InvalidCode {
            get {
                return ResourceManager.GetString("Validation.InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation.StringLength", resourceCulture);
            }
        }
    }
}
