//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_ExternalLoginModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_ExternalLoginModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.ExternalLoginModel", typeof(Areas_Identity_Pages_Account_ExternalLoginModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Error from external provider: {0}.
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Error loading external login information..
        /// </summary>
        public static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Error loading external login information during confirmation..
        /// </summary>
        public static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *{0} logged in with {1} provider..
        /// </summary>
        public static string Log1 {
            get {
                return ResourceManager.GetString("Log1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *User created an account using {0} provider..
        /// </summary>
        public static string Log2 {
            get {
                return ResourceManager.GetString("Log2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You&apos;ve successfully authenticated with &lt;strong&gt;{0}&lt;/strong&gt;. Please enter an email address for this site below and click the Register button to finish logging in..
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Associate your {0} account..
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
    }
}
