//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_Manage_ExternalLoginsModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_Manage_ExternalLoginsModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.Manage.ExternalLoginsMod" +
                            "el", typeof(Areas_Identity_Pages_Account_Manage_ExternalLoginsModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Unexpected error occurred loading external login info for user with ID &apos;{0}&apos;..
        /// </summary>
        public static string Error_CannotLoadExternalLoginForUser {
            get {
                return ResourceManager.GetString("Error.CannotLoadExternalLoginForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The external login &apos;{0}&apos; was added..
        /// </summary>
        public static string Log_LoginAdded {
            get {
                return ResourceManager.GetString("Log.LoginAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The external login &apos;{0}&apos; was not added. External logins can only be associated with one account..
        /// </summary>
        public static string Log_LoginNotAdded {
            get {
                return ResourceManager.GetString("Log.LoginNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The external login &apos;{0}&apos; was not removed..
        /// </summary>
        public static string Log_LoginNotRemoved {
            get {
                return ResourceManager.GetString("Log.LoginNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The external login &apos;{0}&apos; was removed..
        /// </summary>
        public static string Log_LoginRemoved {
            get {
                return ResourceManager.GetString("Log.LoginRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Add another service to log in..
        /// </summary>
        public static string Message_AddAnotherLogin {
            get {
                return ResourceManager.GetString("Message.AddAnotherLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The external login was added..
        /// </summary>
        public static string Message_LoginAdded {
            get {
                return ResourceManager.GetString("Message.LoginAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The external login was not added. External logins can only be associated with one account..
        /// </summary>
        public static string Message_LoginNotAdded {
            get {
                return ResourceManager.GetString("Message.LoginNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The external login was not removed..
        /// </summary>
        public static string Message_LoginNotRemoved {
            get {
                return ResourceManager.GetString("Message.LoginNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The external login was removed..
        /// </summary>
        public static string Message_LoginRemoved {
            get {
                return ResourceManager.GetString("Message.LoginRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Log in using your {0} account.
        /// </summary>
        public static string Message_LoginUsingNamedAccount {
            get {
                return ResourceManager.GetString("Message.LoginUsingNamedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Remove this {0} login from your account.
        /// </summary>
        public static string Message_RemoveThisNamedLogin {
            get {
                return ResourceManager.GetString("Message.RemoveThisNamedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You don&apos;t have external logins..
        /// </summary>
        public static string Message_YouDontHaveLogins {
            get {
                return ResourceManager.GetString("Message.YouDontHaveLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Registered Logins.
        /// </summary>
        public static string Text_RegisteredLogins {
            get {
                return ResourceManager.GetString("Text.RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Remove.
        /// </summary>
        public static string Text_Remove {
            get {
                return ResourceManager.GetString("Text.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Manage your external logins.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
