//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_Manage_TwoFactorAuthenticationModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_Manage_TwoFactorAuthenticationModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.Manage.TwoFactorAuthenti" +
                            "cationModel", typeof(Areas_Identity_Pages_Account_Manage_TwoFactorAuthenticationModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The current browser has been forgotten. When you login again from this browser you will be prompted for your 2fa code..
        /// </summary>
        public static string Message_2FA_BrowserHasForgotten {
            get {
                return ResourceManager.GetString("Message.2FA.BrowserHasForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You should.
        /// </summary>
        public static string Message_Few_1 {
            get {
                return ResourceManager.GetString("Message.Few.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You have.
        /// </summary>
        public static string Message_FewRecoveryCodes_1 {
            get {
                return ResourceManager.GetString("Message.FewRecoveryCodes.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *recovery codes left..
        /// </summary>
        public static string Message_FewRecoveryCodes_2 {
            get {
                return ResourceManager.GetString("Message.FewRecoveryCodes.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *generate a new set of recovery codes.
        /// </summary>
        public static string Message_GenerateCodes {
            get {
                return ResourceManager.GetString("Message.GenerateCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You can.
        /// </summary>
        public static string Message_One_1 {
            get {
                return ResourceManager.GetString("Message.One.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You have 1 recovery code left..
        /// </summary>
        public static string Message_OneRecoveryCode {
            get {
                return ResourceManager.GetString("Message.OneRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You must.
        /// </summary>
        public static string Message_Zero_1 {
            get {
                return ResourceManager.GetString("Message.Zero.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *before you can log in with a recovery code..
        /// </summary>
        public static string Message_Zero_2 {
            get {
                return ResourceManager.GetString("Message.Zero.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You have no recovery codes left..
        /// </summary>
        public static string Message_ZeroRecoveryCodes {
            get {
                return ResourceManager.GetString("Message.ZeroRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Add authenticator app.
        /// </summary>
        public static string Text_AddAuthentificatorApp {
            get {
                return ResourceManager.GetString("Text.AddAuthentificatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Authenticator app.
        /// </summary>
        public static string Text_AuthentificatorApp {
            get {
                return ResourceManager.GetString("Text.AuthentificatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Disable 2FA.
        /// </summary>
        public static string Text_Disable2FA {
            get {
                return ResourceManager.GetString("Text.Disable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Forget this browser.
        /// </summary>
        public static string Text_ForgetThisBrowser {
            get {
                return ResourceManager.GetString("Text.ForgetThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Reset authenticator app.
        /// </summary>
        public static string Text_ResetAuthentificatorApp {
            get {
                return ResourceManager.GetString("Text.ResetAuthentificatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Reset recovery codes.
        /// </summary>
        public static string Text_ResetRecoveryCodes {
            get {
                return ResourceManager.GetString("Text.ResetRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Setup authenticator app.
        /// </summary>
        public static string Text_SetupAuthentificatorApp {
            get {
                return ResourceManager.GetString("Text.SetupAuthentificatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Two-factor authentication (2FA).
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
