//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_RegisterModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_RegisterModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.RegisterModel", typeof(Areas_Identity_Pages_Account_RegisterModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Log in using your {0} account.
        /// </summary>
        public static string Format_LoginUsingExternalAuthenticationAccount {
            get {
                return ResourceManager.GetString("Format.LoginUsingExternalAuthenticationAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Confirm password.
        /// </summary>
        public static string Model_ConfirmPassword {
            get {
                return ResourceManager.GetString("Model.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Customer reference.
        /// </summary>
        public static string Model_CustomerReferenceId {
            get {
                return ResourceManager.GetString("Model.CustomerReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Email address.
        /// </summary>
        public static string Model_Email {
            get {
                return ResourceManager.GetString("Model.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Accept EULA.
        /// </summary>
        public static string Model_Eula {
            get {
                return ResourceManager.GetString("Model.Eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Accept GDPR.
        /// </summary>
        public static string Model_GDPR {
            get {
                return ResourceManager.GetString("Model.GDPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Display name.
        /// </summary>
        public static string Model_Name {
            get {
                return ResourceManager.GetString("Model.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Password.
        /// </summary>
        public static string Model_Password {
            get {
                return ResourceManager.GetString("Model.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Create a new account..
        /// </summary>
        public static string Text_CreateNewAccount {
            get {
                return ResourceManager.GetString("Text.CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *There are no external authentication services configured..
        /// </summary>
        public static string Text_NoExternalAuthenticationProvidersConfigured {
            get {
                return ResourceManager.GetString("Text.NoExternalAuthenticationProvidersConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Use another service to register..
        /// </summary>
        public static string Text_UseExternalAuthenticationToRegister {
            get {
                return ResourceManager.GetString("Text.UseExternalAuthenticationToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Register.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You must accept EULA to register..
        /// </summary>
        public static string Validation_EulaNotAccepted {
            get {
                return ResourceManager.GetString("Validation.EulaNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You must accept GDPR to register..
        /// </summary>
        public static string Validation_GdprNotAccepted {
            get {
                return ResourceManager.GetString("Validation.GdprNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string Validation_PasswordLength {
            get {
                return ResourceManager.GetString("Validation.PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The password and confirmation password do not match..
        /// </summary>
        public static string Validation_PasswordsMismatch {
            get {
                return ResourceManager.GetString("Validation.PasswordsMismatch", resourceCulture);
            }
        }
    }
}
