//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_Manage_DeletePersonalDataModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_Manage_DeletePersonalDataModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.Manage.DeletePersonalDat" +
                            "aModel", typeof(Areas_Identity_Pages_Account_Manage_DeletePersonalDataModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Unexpected error occurred deleting user with ID &apos;{0}&apos;..
        /// </summary>
        public static string Error_UnexpectedError {
            get {
                return ResourceManager.GetString("Error.UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *User with ID &apos;{0}&apos; deleted themselves..
        /// </summary>
        public static string Message_UserDeleted {
            get {
                return ResourceManager.GetString("Message.UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string Message_Warning {
            get {
                return ResourceManager.GetString("Message.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Password.
        /// </summary>
        public static string Model_Password {
            get {
                return ResourceManager.GetString("Model.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Delete data and close my account.
        /// </summary>
        public static string Text_DeleteDataAndCloseAccount {
            get {
                return ResourceManager.GetString("Text.DeleteDataAndCloseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Delete Personal Data.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Incorrect password..
        /// </summary>
        public static string Validation_InvalidPassword {
            get {
                return ResourceManager.GetString("Validation.InvalidPassword", resourceCulture);
            }
        }
    }
}
