//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Areas_Identity_Pages_Account_Manage_SetPasswordModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Identity_Pages_Account_Manage_SetPasswordModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Areas.Identity.Pages.Account.Manage.SetPasswordModel", typeof(Areas_Identity_Pages_Account_Manage_SetPasswordModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *User with ID &apos;{0}&apos; has set password..
        /// </summary>
        public static string Log_Success {
            get {
                return ResourceManager.GetString("Log.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string Message_1 {
            get {
                return ResourceManager.GetString("Message.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Your password has been set..
        /// </summary>
        public static string Message_PasswordSet {
            get {
                return ResourceManager.GetString("Message.PasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Confirm new password.
        /// </summary>
        public static string Model_ConfirmPassword {
            get {
                return ResourceManager.GetString("Model.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *New password.
        /// </summary>
        public static string Model_NewPassword {
            get {
                return ResourceManager.GetString("Model.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Set password.
        /// </summary>
        public static string Text_SetPassword {
            get {
                return ResourceManager.GetString("Text.SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Set password.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Set your password.
        /// </summary>
        public static string Title_2 {
            get {
                return ResourceManager.GetString("Title-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string Validation_PasswordLength {
            get {
                return ResourceManager.GetString("Validation.PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The new password and confirmation password do not match..
        /// </summary>
        public static string Validation_PasswordsMismatch {
            get {
                return ResourceManager.GetString("Validation.PasswordsMismatch", resourceCulture);
            }
        }
    }
}
