//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLicense.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLicense.Server.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebLicense.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Unable to load user with ID &apos;{0}&apos;..
        /// </summary>
        public static string Error_Format_UnableLoadUserWithId {
            get {
                return ResourceManager.GetString("Error.Format.UnableLoadUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Format_LoggedInWelcome {
            get {
                return ResourceManager.GetString("Format.LoggedInWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Change your account settings.
        /// </summary>
        public static string Text_ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("Text.ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Close.
        /// </summary>
        public static string Text_Close {
            get {
                return ResourceManager.GetString("Text.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Create.
        /// </summary>
        public static string Text_Create {
            get {
                return ResourceManager.GetString("Text.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Email.
        /// </summary>
        public static string Text_Email {
            get {
                return ResourceManager.GetString("Text.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *External logins.
        /// </summary>
        public static string Text_ExternalLogins {
            get {
                return ResourceManager.GetString("Text.ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Log in.
        /// </summary>
        public static string Text_Login {
            get {
                return ResourceManager.GetString("Text.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Logout.
        /// </summary>
        public static string Text_Logout {
            get {
                return ResourceManager.GetString("Text.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Manage.
        /// </summary>
        public static string Text_Manage {
            get {
                return ResourceManager.GetString("Text.Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Manage your account.
        /// </summary>
        public static string Text_ManageYourAccount {
            get {
                return ResourceManager.GetString("Text.ManageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Password.
        /// </summary>
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Personal data.
        /// </summary>
        public static string Text_PersonalData {
            get {
                return ResourceManager.GetString("Text.PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Profile.
        /// </summary>
        public static string Text_Profile {
            get {
                return ResourceManager.GetString("Text.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Register.
        /// </summary>
        public static string Text_Register {
            get {
                return ResourceManager.GetString("Text.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Resend.
        /// </summary>
        public static string Text_Resend {
            get {
                return ResourceManager.GetString("Text.Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Reset.
        /// </summary>
        public static string Text_Reset {
            get {
                return ResourceManager.GetString("Text.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Save.
        /// </summary>
        public static string Text_Save {
            get {
                return ResourceManager.GetString("Text.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Submit.
        /// </summary>
        public static string Text_Submit {
            get {
                return ResourceManager.GetString("Text.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Two-factor authentication.
        /// </summary>
        public static string Text_TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("Text.TwoFactorAuthentication", resourceCulture);
            }
        }
    }
}
